# Generated by Django 6.0.6 on 2026-06-20 05:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='器材名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('total_quantity', models.IntegerField(default=1, verbose_name='总库存')),
                ('available_quantity', models.IntegerField(default=1, verbose_name='可用库存')),
                ('status', models.CharField(choices=[('normal', '正常'), ('damaged', '损坏')], default='normal', max_length=20, verbose_name='状态')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('image_url', models.URLField(blank=True, verbose_name='图片链接')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '器材',
                'verbose_name_plural': '器材',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DamageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='损坏描述')),
                ('quantity', models.IntegerField(default=1, verbose_name='损坏数量')),
                ('status', models.CharField(choices=[('reported', '已上报'), ('processing', '处理中'), ('resolved', '已处理')], default='reported', max_length=20, verbose_name='状态')),
                ('handle_note', models.TextField(blank=True, verbose_name='处理备注')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_damages', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_damages', to=settings.AUTH_USER_MODEL, verbose_name='上报人')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_records', to='equipment.equipment', verbose_name='器材')),
            ],
            options={
                'verbose_name': '损坏记录',
                'verbose_name_plural': '损坏记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(verbose_name='预约日期')),
                ('time_slot', models.CharField(choices=[('morning', '上午 (8:00-12:00)'), ('afternoon', '下午 (14:00-18:00)')], max_length=20, verbose_name='时段')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('picked', '已领取'), ('returned', '已归还'), ('overdue', '已逾期')], default='pending', max_length=20, verbose_name='状态')),
                ('purpose', models.TextField(blank=True, verbose_name='用途')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('reject_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('picked_at', models.DateTimeField(blank=True, null=True, verbose_name='领取时间')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('return_note', models.TextField(blank=True, verbose_name='归还备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reservations', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='equipment.equipment', verbose_name='器材')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='预约人')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('in', '入库'), ('out', '出库')], max_length=10, verbose_name='流动类型')),
                ('flow_reason', models.CharField(choices=[('purchase', '采购入库'), ('reserve', '预约出库'), ('return', '归还入库'), ('damage', '损坏出库'), ('adjust', '库存调整')], max_length=20, verbose_name='变动原因')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('balance_after', models.IntegerField(verbose_name='变动后库存')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_flows', to='equipment.equipment', verbose_name='器材')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_flows', to='equipment.reservation', verbose_name='关联预约')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('approve', '批准'), ('reject', '拒绝'), ('cancel', '取消'), ('pick', '领取'), ('return', '归还'), ('damage', '损坏'), ('overdue', '逾期')], max_length=20, verbose_name='操作类型')),
                ('target_type', models.CharField(max_length=50, verbose_name='目标类型')),
                ('target_id', models.IntegerField(verbose_name='目标ID')),
                ('details', models.TextField(blank=True, verbose_name='详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计记录',
                'verbose_name_plural': '审计记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='equipment_a_target__ac41f5_idx')],
            },
        ),
    ]
