# Generated by Django 6.0.6 on 2026-06-20 12:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('approve', '批准'), ('reject', '拒绝'), ('cancel', '取消'), ('pick', '领取'), ('return', '归还'), ('damage', '损坏'), ('overdue', '逾期'), ('waitlist_create', '候补创建'), ('waitlist_cancel', '候补取消'), ('waitlist_promote', '候补转预约'), ('waitlist_skip', '候补跳过'), ('waitlist_reject', '候补拒绝')], max_length=20, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('damaged', '损坏'), ('offline', '下架')], default='normal', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(verbose_name='预约日期')),
                ('time_slot', models.CharField(choices=[('morning', '上午 (8:00-12:00)'), ('afternoon', '下午 (14:00-18:00)')], max_length=20, verbose_name='时段')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('queue_position', models.IntegerField(verbose_name='排队顺序')),
                ('status', models.CharField(choices=[('waiting', '等待中'), ('cancelled', '已取消'), ('promoted', '已转预约'), ('rejected', '已拒绝'), ('skipped', '已跳过')], default='waiting', max_length=20, verbose_name='状态')),
                ('reject_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='equipment.equipment', verbose_name='器材')),
                ('promoted_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_waitlist', to='equipment.reservation', verbose_name='转为的预约')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '候补记录',
                'verbose_name_plural': '候补记录',
                'ordering': ['queue_position'],
                'indexes': [models.Index(fields=['equipment', 'reservation_date', 'time_slot', 'status'], name='equipment_w_equipme_a8ff33_idx')],
            },
        ),
    ]
